Repository ImamWD/EcoTrack, pull requests merged in 2023-12, with the labels that each got.

#3 Crud-weather
  api/routes/weather.js
  app.js
Labels: enhancement, Imam

#4 EDU-CRUD
  api/routes/Edu.js
  api/routes/weather.js
  app.js
Labels: enhancement, Imam

#5 Reporting-Crud
  api/routes/report.js
  app.js
Labels: Imam

#6 feedback-crud
  api/routes/feedback.js
  api/routes/report.js
  app.js
Labels: enhancement, Imam

#7 Conc-client-crud
  api/routes/conc.js
  app.js
Labels: enhancement, Imam

#8 login-logout
  api/routes/login.js
  app.js
  uploads/1703375117758-Screenshot_2021-03-26 quiz 1 Attempt review(12).png
  uploads/1703375140117-Screenshot_2021-03-26 quiz 1 Attempt review(12).png
Labels: enhancement, Imam

#9 DB
  ecotrack.sql
Labels: enhancement, Imam

#10 clear-images
  uploads/1703275830952-403603283_254526674306534_140076168700774680_n.jpg
  uploads/1703275833492-403603283_254526674306534_140076168700774680_n.jpg
  uploads/1703275838542-403603283_254526674306534_140076168700774680_n.jpg
  uploads/1703276991375-403603283_254526674306534_140076168700774680_n.jpg
  uploads/1703288709327-ffffffffffffffffff.jpg
  uploads/1703288825385-Screenshot_2021-03-26 quiz 1 Attempt review(12).png
  uploads/1703292013769-111111112.png
  uploads/1703375117758-Screenshot_2021-03-26 quiz 1 Attempt review(12).png
  uploads/1703375140117-Screenshot_2021-03-26 quiz 1 Attempt review(12).png
  uploads/1703376456276-start.png
Labels: enhancement, Imam

#13 Zayddwikat
  api/routes/SevenDayWeather.js
  api/routes/TodayWeather.js
  api/routes/allusersSameConcerents.js
  api/routes/feedback.js
  api/routes/showConcerentAlert.js
  api/routes/showLocationAlert.js
  app.js
Labels: enhancement, ZaydFalah

#12 Test
  api/routes/Test.js
  api/routes/c_education.js
  api/routes/c_feedback.js
  api/routes/c_report.js
  api/routes/report.js
  app.js
Labels: enhancement, ZaidSadAlDeen

#14 final update
  app.js
Labels: enhancement, ZaidSadAlDeen

#15 Test2
  api/routes/RankForloctions.js
  app.js
Labels: enhancement, ZaydFalah
